create table if not exists public.inscricoes (
  id uuid primary key default gen_random_uuid(),
  nome_completo text not null,
  telefone text not null,
  cpf text,
  tipo_sanguineo text,
  grupo text,
  cidade text,
  tamanho_camiseta text,
  veiculo text,
  comprovante_url text,
  observacoes text,
  solidaria boolean not null default false,
  termos boolean not null default false,
  numero_inscricao bigint generated by default as identity unique,
  camiseta_garantida boolean generated always as (numero_inscricao <= 200) stored,
  voucher_codigo text unique,
  voucher_emitido_em timestamptz,
  status text not null default 'pendente',
  created_at timestamptz not null default now()
);

alter table public.inscricoes enable row level security;

create policy "Permitir envio publico de inscricoes"
on public.inscricoes
for insert
to anon
with check (
  nome_completo is not null
  and length(trim(nome_completo)) >= 3
  and telefone is not null
  and length(trim(telefone)) >= 8
  and solidaria is true
  and termos is true
  and status = 'voucher-gerado'
  and voucher_codigo like 'TR-%'
  and voucher_emitido_em is not null
);

revoke insert on table public.inscricoes from anon;
grant select, insert, update, delete on table public.inscricoes to service_role;

create or replace function public.criar_inscricao_publica(dados jsonb)
returns table (
  voucher_codigo text,
  numero_inscricao bigint,
  camiseta_garantida boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  nova_inscricao public.inscricoes%rowtype;
begin
  if length(trim(coalesce(dados->>'nome_completo', ''))) < 3 then
    raise exception 'Nome completo invalido';
  end if;

  if length(trim(coalesce(dados->>'telefone', ''))) < 8 then
    raise exception 'Telefone invalido';
  end if;

  if coalesce((dados->>'solidaria')::boolean, false) is not true then
    raise exception 'Confirmacao solidaria obrigatoria';
  end if;

  if coalesce((dados->>'termos')::boolean, false) is not true then
    raise exception 'Confirmacao dos termos obrigatoria';
  end if;

  if coalesce(dados->>'status', '') <> 'voucher-gerado' then
    raise exception 'Status invalido';
  end if;

  if coalesce(dados->>'voucher_codigo', '') not like 'TR-%' then
    raise exception 'Voucher invalido';
  end if;

  insert into public.inscricoes (
    nome_completo,
    telefone,
    cpf,
    tipo_sanguineo,
    grupo,
    cidade,
    tamanho_camiseta,
    veiculo,
    comprovante_url,
    observacoes,
    solidaria,
    termos,
    voucher_codigo,
    voucher_emitido_em,
    status
  ) values (
    trim(dados->>'nome_completo'),
    trim(dados->>'telefone'),
    nullif(trim(coalesce(dados->>'cpf', '')), ''),
    nullif(trim(coalesce(dados->>'tipo_sanguineo', '')), ''),
    nullif(trim(coalesce(dados->>'grupo', '')), ''),
    nullif(trim(coalesce(dados->>'cidade', '')), ''),
    nullif(trim(coalesce(dados->>'tamanho_camiseta', '')), ''),
    nullif(trim(coalesce(dados->>'veiculo', '')), ''),
    nullif(trim(coalesce(dados->>'comprovante_url', '')), ''),
    nullif(trim(coalesce(dados->>'observacoes', '')), ''),
    (dados->>'solidaria')::boolean,
    (dados->>'termos')::boolean,
    dados->>'voucher_codigo',
    coalesce((dados->>'voucher_emitido_em')::timestamptz, now()),
    dados->>'status'
  )
  returning * into nova_inscricao;

  voucher_codigo := nova_inscricao.voucher_codigo;
  numero_inscricao := nova_inscricao.numero_inscricao;
  camiseta_garantida := nova_inscricao.camiseta_garantida;
  created_at := nova_inscricao.created_at;
  return next;
end;
$$;

revoke all on function public.criar_inscricao_publica(jsonb) from public;
grant execute on function public.criar_inscricao_publica(jsonb) to anon;

-- Por seguranca, nao ha policy publica de SELECT nem INSERT direto para anon.
-- O formulario publico usa a funcao criar_inscricao_publica, que valida os dados
-- e retorna apenas os metadados necessarios para o voucher.
