create table if not exists public.inscricoes (
  id uuid primary key default gen_random_uuid(),
  nome_completo text not null,
  usuario_id uuid,
  usuario_email text,
  telefone text not null,
  cpf text,
  tipo_sanguineo text,
  grupo text,
  cidade text,
  tamanho_camiseta text,
  veiculo text,
  comprovante_url text,
  observacoes text,
  solidaria boolean not null default false,
  termos boolean not null default false,
  numero_inscricao bigint generated by default as identity unique,
  camiseta_garantida boolean generated always as (numero_inscricao <= 200) stored,
  voucher_codigo text unique,
  voucher_emitido_em timestamptz,
  status text not null default 'pendente',
  mercado_pago_order_id text,
  mercado_pago_payment_id text,
  pagamento_status text,
  pago_em timestamptz,
  created_at timestamptz not null default now()
);

alter table public.inscricoes enable row level security;

-- Inscricao exige login: anon nao tem policy nem privilegio de INSERT.
drop policy if exists "Permitir envio publico de inscricoes" on public.inscricoes;

alter table public.inscricoes
  add column if not exists mercado_pago_order_id text,
  add column if not exists mercado_pago_payment_id text,
  add column if not exists pagamento_status text,
  add column if not exists pago_em timestamptz;

create unique index if not exists inscricoes_mercado_pago_order_id_uidx
on public.inscricoes (mercado_pago_order_id)
where mercado_pago_order_id is not null;

create table if not exists public.pagamentos_pix_pendentes (
  mercado_pago_order_id text primary key,
  usuario_id uuid not null,
  usuario_email text,
  dados jsonb not null,
  amount numeric(10,2) not null,
  status text not null default 'aguardando_pagamento',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.pagamentos_pix_pendentes enable row level security;
revoke insert on table public.inscricoes from anon;
revoke insert on table public.inscricoes from authenticated;
grant select on table public.inscricoes to authenticated;
grant select, insert, update, delete on table public.inscricoes to service_role;
revoke all on table public.pagamentos_pix_pendentes from anon;
revoke all on table public.pagamentos_pix_pendentes from authenticated;
grant select, insert, update, delete on table public.pagamentos_pix_pendentes to service_role;

drop policy if exists "Permitir envio autenticado de inscricoes" on public.inscricoes;
drop policy if exists "Permitir envio publico de inscricoes" on public.inscricoes;

drop policy if exists "Participante pode ler seus vouchers" on public.inscricoes;
create policy "Participante pode ler seus vouchers"
on public.inscricoes
for select
to authenticated
using (usuario_id = (select auth.uid()));

create or replace function public.criar_inscricao_publica(dados jsonb)
returns table (
  voucher_codigo text,
  numero_inscricao bigint,
  camiseta_garantida boolean,
  created_at timestamptz
)
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  nova_inscricao public.inscricoes%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'Login obrigatorio';
  end if;

  if length(trim(coalesce(dados->>'nome_completo', ''))) < 3 then
    raise exception 'Nome completo invalido';
  end if;

  if length(trim(coalesce(dados->>'telefone', ''))) < 8 then
    raise exception 'Telefone invalido';
  end if;

  if coalesce((dados->>'solidaria')::boolean, false) is not true then
    raise exception 'Confirmacao solidaria obrigatoria';
  end if;

  if coalesce((dados->>'termos')::boolean, false) is not true then
    raise exception 'Confirmacao dos termos obrigatoria';
  end if;

  if coalesce(dados->>'status', '') <> 'voucher-gerado' then
    raise exception 'Status invalido';
  end if;

  if coalesce(dados->>'voucher_codigo', '') not like 'TR-%' then
    raise exception 'Voucher invalido';
  end if;

  insert into public.inscricoes (
    nome_completo,
    usuario_id,
    usuario_email,
    telefone,
    cpf,
    tipo_sanguineo,
    grupo,
    cidade,
    tamanho_camiseta,
    veiculo,
    comprovante_url,
    observacoes,
    solidaria,
    termos,
    voucher_codigo,
    voucher_emitido_em,
    status
  ) values (
    trim(dados->>'nome_completo'),
    (select auth.uid()),
    current_setting('request.jwt.claims', true)::jsonb->>'email',
    trim(dados->>'telefone'),
    nullif(trim(coalesce(dados->>'cpf', '')), ''),
    nullif(trim(coalesce(dados->>'tipo_sanguineo', '')), ''),
    nullif(trim(coalesce(dados->>'grupo', '')), ''),
    nullif(trim(coalesce(dados->>'cidade', '')), ''),
    nullif(trim(coalesce(dados->>'tamanho_camiseta', '')), ''),
    nullif(trim(coalesce(dados->>'veiculo', '')), ''),
    nullif(trim(coalesce(dados->>'comprovante_url', '')), ''),
    nullif(trim(coalesce(dados->>'observacoes', '')), ''),
    (dados->>'solidaria')::boolean,
    (dados->>'termos')::boolean,
    dados->>'voucher_codigo',
    coalesce((dados->>'voucher_emitido_em')::timestamptz, now()),
    dados->>'status'
  )
  returning * into nova_inscricao;

  voucher_codigo := nova_inscricao.voucher_codigo;
  numero_inscricao := nova_inscricao.numero_inscricao;
  camiseta_garantida := nova_inscricao.camiseta_garantida;
  created_at := nova_inscricao.created_at;
  return next;
end;
$$;

revoke all on function public.criar_inscricao_publica(jsonb) from public;
revoke execute on function public.criar_inscricao_publica(jsonb) from anon;
revoke execute on function public.criar_inscricao_publica(jsonb) from authenticated;

-- Por seguranca, nao ha policy publica de SELECT nem INSERT direto para anon.
-- O frontend tambem nao tem INSERT autenticado. O voucher agora e inserido apenas
-- pelo backend depois que a API do Mercado Pago confirma o pagamento Pix.
